SELECT A.APNT_NO, B.PT_NAME, A.PT_NO, A.MCDP_CD, C.DR_NAME, A.APNT_YMD
FROM APPOINTMENT A JOIN PATIENT B ON A.PT_NO = B.PT_NO JOIN DOCTOR C ON C.MCDP_CD = A.MCDP_CD AND C.DR_ID = A.MDDR_ID
WHERE A.APNT_CNCL_YN = 'N' AND A.APNT_YMD LIKE '2022-04-13%' AND C.MCDP_CD = 'CS'
ORDER BY A.APNT_YMD;

